inherit_from:
  - https://raw.githubusercontent.com/trailblazer/meta/master/rubocop.yml
  - .rubocop_todo.yml

# Trailblazer uses constant named methods for macros.
Naming/MethodName:
  Enabled: false
